/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface CreateInterface extends Interface {
  getFunction(nameOrSignature: "create"): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "MarketOpen"): EventFragment;

  encodeFunctionData(
    functionFragment: "create",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "create", data: BytesLike): Result;
}

export namespace MarketOpenEvent {
  export type InputTuple = [
    _market: AddressLike,
    _base: AddressLike,
    _quote: AddressLike
  ];
  export type OutputTuple = [_market: string, _base: string, _quote: string];
  export interface OutputObject {
    _market: string;
    _base: string;
    _quote: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Create extends BaseContract {
  connect(runner?: ContractRunner | null): Create;
  waitForDeployment(): Promise<this>;

  interface: CreateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  create: TypedContractMethod<
    [_base: AddressLike, _quote: AddressLike, _initialPrice: BigNumberish],
    [string],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "create"
  ): TypedContractMethod<
    [_base: AddressLike, _quote: AddressLike, _initialPrice: BigNumberish],
    [string],
    "nonpayable"
  >;

  getEvent(
    key: "MarketOpen"
  ): TypedContractEvent<
    MarketOpenEvent.InputTuple,
    MarketOpenEvent.OutputTuple,
    MarketOpenEvent.OutputObject
  >;

  filters: {
    "MarketOpen(address,address,address)": TypedContractEvent<
      MarketOpenEvent.InputTuple,
      MarketOpenEvent.OutputTuple,
      MarketOpenEvent.OutputObject
    >;
    MarketOpen: TypedContractEvent<
      MarketOpenEvent.InputTuple,
      MarketOpenEvent.OutputTuple,
      MarketOpenEvent.OutputObject
    >;
  };
}
