/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IOrderbook,
  IOrderbookInterface,
} from "../../../../contracts/services/orderbook/IOrderbook";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
    ],
    name: "order",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IOrderbook__factory {
  static readonly abi = _abi;
  static createInterface(): IOrderbookInterface {
    return new Interface(_abi) as IOrderbookInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IOrderbook {
    return new Contract(address, _abi, runner) as unknown as IOrderbook;
  }
}
