/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
export type { DiamondContract } from "./DiamondContract";
export type { DiamondContractManager } from "./DiamondContractManager";
export type { DiamondFacade } from "./DiamondFacade";
