/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IDiamond__factory } from "./IDiamond__factory";
export { IDiamondCut__factory } from "./IDiamondCut__factory";
