/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface OrderbookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkPermission"
      | "facet"
      | "setInterface"
      | "setPermission"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkPermission",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "facet", values: [BytesLike]): string;
  encodeFunctionData(
    functionFragment: "setInterface",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setPermission",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "facet", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPermission",
    data: BytesLike
  ): Result;
}

export interface Orderbook extends BaseContract {
  connect(runner?: ContractRunner | null): Orderbook;
  waitForDeployment(): Promise<this>;

  interface: OrderbookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkPermission: TypedContractMethod<
    [_owner: AddressLike],
    [boolean],
    "view"
  >;

  facet: TypedContractMethod<[_funct: BytesLike], [string], "view">;

  setInterface: TypedContractMethod<
    [_funct: BytesLike, _state: boolean],
    [void],
    "nonpayable"
  >;

  setPermission: TypedContractMethod<
    [_owner: AddressLike, _permission: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkPermission"
  ): TypedContractMethod<[_owner: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "facet"
  ): TypedContractMethod<[_funct: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "setInterface"
  ): TypedContractMethod<
    [_funct: BytesLike, _state: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setPermission"
  ): TypedContractMethod<
    [_owner: AddressLike, _permission: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
