/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export declare namespace DiamondContractManager {
  export type FacetStruct = { addr: AddressLike; functs: BytesLike[] };

  export type FacetStructOutput = [addr: string, functs: string[]] & {
    addr: string;
    functs: string[];
  };
}

export interface OrderbookInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "checkInterface"
      | "checkPermission"
      | "facet"
      | "facets"
      | "functs"
      | "getFacets"
      | "setInterface"
      | "setOwner"
      | "setPermission"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "checkInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "checkPermission",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "facet", values: [BytesLike]): string;
  encodeFunctionData(functionFragment: "facets", values?: undefined): string;
  encodeFunctionData(functionFragment: "functs", values: [AddressLike]): string;
  encodeFunctionData(functionFragment: "getFacets", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setInterface",
    values: [BytesLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setOwner",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPermission",
    values: [AddressLike, boolean]
  ): string;

  decodeFunctionResult(
    functionFragment: "checkInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkPermission",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "facet", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "facets", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "functs", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getFacets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setPermission",
    data: BytesLike
  ): Result;
}

export interface Orderbook extends BaseContract {
  connect(runner?: ContractRunner | null): Orderbook;
  waitForDeployment(): Promise<this>;

  interface: OrderbookInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  checkInterface: TypedContractMethod<
    [_interface: BytesLike],
    [boolean],
    "nonpayable"
  >;

  checkPermission: TypedContractMethod<
    [_owner: AddressLike],
    [boolean],
    "view"
  >;

  facet: TypedContractMethod<[_funct: BytesLike], [string], "view">;

  facets: TypedContractMethod<[], [string[]], "view">;

  functs: TypedContractMethod<[_facet: AddressLike], [string[]], "view">;

  getFacets: TypedContractMethod<
    [],
    [DiamondContractManager.FacetStructOutput[]],
    "view"
  >;

  setInterface: TypedContractMethod<
    [_funct: BytesLike, _state: boolean],
    [void],
    "nonpayable"
  >;

  setOwner: TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;

  setPermission: TypedContractMethod<
    [_owner: AddressLike, _permission: boolean],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "checkInterface"
  ): TypedContractMethod<[_interface: BytesLike], [boolean], "nonpayable">;
  getFunction(
    nameOrSignature: "checkPermission"
  ): TypedContractMethod<[_owner: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "facet"
  ): TypedContractMethod<[_funct: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "facets"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "functs"
  ): TypedContractMethod<[_facet: AddressLike], [string[]], "view">;
  getFunction(
    nameOrSignature: "getFacets"
  ): TypedContractMethod<
    [],
    [DiamondContractManager.FacetStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "setInterface"
  ): TypedContractMethod<
    [_funct: BytesLike, _state: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setOwner"
  ): TypedContractMethod<[_owner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPermission"
  ): TypedContractMethod<
    [_owner: AddressLike, _permission: boolean],
    [void],
    "nonpayable"
  >;

  filters: {};
}
