/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../../../common";
import type {
  ERROR,
  ERRORInterface,
} from "../../../../contracts/types/Error.sol/ERROR";

const _abi = [
  {
    inputs: [
      {
        internalType: "enum ERROR.TYPE",
        name: "__",
        type: "uint8",
      },
    ],
    name: "CODE",
    type: "error",
  },
] as const;

const _bytecode =
  "0x60566050600b82828239805160001a6073146043577f4e487b7100000000000000000000000000000000000000000000000000000000600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220fa14299ebccc315c236e2eee6d54e46e86fc38ef7101bd0221a6e1d57522d43364736f6c63430008140033";

type ERRORConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ERRORConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ERROR__factory extends ContractFactory {
  constructor(...args: ERRORConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ERROR & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ERROR__factory {
    return super.connect(runner) as ERROR__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ERRORInterface {
    return new Interface(_abi) as ERRORInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ERROR {
    return new Contract(address, _abi, runner) as unknown as ERROR;
  }
}
